#spring.application.name=eureka-server
#
##standard port for eureka server
#server.port=8761
#
#
#eureka.instance.hostname=localhost
##this is the server so it should not register with itself
## this project acts as server
#eureka.client.register-with-eureka=false
##It should not fetch registry from itself
#eureka.client.fetch-registry=false
#
#
#eureka.client.service-url.defaultZone=http:${eureka.instance.hostname}:${server.port}/eureka/
spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.enable-self-preservation=false

spring.freemarker.check-template-location=false